services:
  client:
    build: ./client
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./client:/client/src/app
    links:
      - api

  api:
    build: ./api
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - ./api:/api
      - /api/node_modules
