export { Burger } from './Burger/Burger'
export { Menu } from './Menu/Menu'
export { Navbar } from './Navbar/Navbar'
export { Login } from './Login/Login'
export { Register } from './Login/Register'

//Pages
export { Base } from './pages/Base'
export { Home } from './pages/Home'
export { Student } from './pages/Student'
export { Kontakt } from './pages/Kontakt'
export { About } from './pages/About'
export { Groups } from './pages/Groups'
export { Fadderuke } from './pages/Fadderuke'
export { Trondheim } from './pages/Trondheim'
export { Historie } from './pages/Historie'
export { Vedtekter } from './pages/Vedtekter'
