export { Burger } from './Burger/Burger'
export { Menu } from './Menu/Menu'
export { Navbar } from './Navbar/Navbar'
export { Login } from './Login/Login'
export { Register } from './Login/Register'
export { Footer } from './Footer/Footer'

//Pages
export { Base } from 'Components/pages/Base'
export { Home } from 'Components/pages/Home'
export { Student } from 'Components/pages/Student'
export { Kontakt } from 'Components/pages/Kontakt'
export { About } from 'Components/pages/About'
export { Groups } from 'Components/pages/Groups'
export { Fadderuke } from 'Components/pages/Fadderuke'
export { Trondheim } from 'Components/pages/Trondheim'
export { Historie } from 'Components/pages/Historie'
export { Vedtekter } from 'Components/pages/Vedtekter'
export { Collegiet } from 'Components/pages/Collegiet'
export { Undergruppe } from 'Components/pages/Undergruppe'
export { PageNotFound } from 'Components/pages/PageNotFound'
export { TempPage } from 'Components/pages/TempPage'
export { Arrangementer } from 'Components/pages/Arrangementer'
export { SignIn } from 'Components/pages/SignIn'
